"""Write a generated ``Dataset`` into the database, or export it as CSV files."""

import csv
import json
from pathlib import Path
from typing import Any

from sqlalchemy import func, insert, select, text
from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine

import app.models  # noqa: F401  (registers every table)
from app.models.database import Base
from app.seed.generator import TABLES, Dataset


async def database_has_shop_data(engine: AsyncEngine) -> bool:
    async with engine.connect() as conn:
        count = await conn.scalar(select(func.count()).select_from(Base.metadata.tables["shops"]))
    return bool(count)


async def reset_all_tables(conn: AsyncConnection) -> None:
    """Empty every application table (shop data and platform data)."""
    tables = [t for t in Base.metadata.sorted_tables]
    if conn.dialect.name == "postgresql":
        names = ", ".join(f'"{t.name}"' for t in tables)
        await conn.execute(text(f"TRUNCATE {names} RESTART IDENTITY CASCADE"))
    else:
        for table in reversed(tables):
            await conn.execute(table.delete())


async def load_dataset(engine: AsyncEngine, dataset: Dataset, *, reset: bool) -> dict[str, int]:
    """Insert every table in dependency order, in one transaction."""
    async with engine.begin() as conn:
        if reset:
            await reset_all_tables(conn)
        for name in TABLES:
            rows = dataset.rows(name)
            if rows:
                await conn.execute(insert(Base.metadata.tables[name]), rows)
    return dataset.counts()


def _csv_value(value: Any) -> Any:
    if value is None:
        return ""
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return value


def export_csv(dataset: Dataset, directory: Path) -> list[Path]:
    """One CSV per table plus edge_cases.json, for browsing the data in an editor."""
    directory.mkdir(parents=True, exist_ok=True)
    written = []
    for name in TABLES:
        rows = dataset.rows(name)
        path = directory / f"{name}.csv"
        with path.open("w", newline="", encoding="utf-8") as handle:
            if rows:
                writer = csv.DictWriter(
                    handle, fieldnames=list(rows[0].keys()), lineterminator="\n"
                )
                writer.writeheader()
                for row in rows:
                    writer.writerow({key: _csv_value(value) for key, value in row.items()})
        written.append(path)
    edge_path = directory / "edge_cases.json"
    edge_path.write_text(
        json.dumps(dataset.edge_cases, indent=2, default=str) + "\n",
        encoding="utf-8",
        newline="\n",  # LF on every OS, matching .gitattributes
    )
    written.append(edge_path)
    return written


def edge_cases_markdown(dataset: Dataset) -> str:
    """Human-readable list of the planted edge cases and what the agents should do."""
    lines = [
        "# Planted edge cases",
        "",
        f"Generated by `python -m scripts.seed` (seed {dataset.seed}, today = {dataset.anchor}).",
        "Each case is a situation the agents must handle correctly; the evaluation set",
        "(Phase 8) checks them. Regenerate this file whenever the generator changes.",
        "",
        "| Case | Shop | Records | What the agents should do |",
        "| --- | --- | --- | --- |",
    ]
    for key, case in dataset.edge_cases.items():
        records = ", ".join(f"{k}={v}" for k, v in case.items() if k not in {"shop_id", "expect"})
        lines.append(f"| `{key}` | {case['shop_id']} | {records} | {case['expect']} |")
    return "\n".join(lines) + "\n"
