"""add langgraph checkpoint tables

The agent graph saves its state here after every step (app/graph/checkpointer.py), so a
workflow can pause for an approval and resume later. Like every table, these get row
level security (see 50ab14e57baa): Supabase's Data API can read nothing, while the
app, which connects as the table owner, is unaffected.

Revision ID: edcdc407c48d
Revises: 50ab14e57baa
Create Date: 2026-10-09 12:03:52.509805

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edcdc407c48d"
down_revision: str | Sequence[str] | None = "50ab14e57baa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = ["graph_checkpoints", "graph_checkpoint_blobs", "graph_checkpoint_writes"]


def _set_rls(enabled: bool) -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    action = "ENABLE" if enabled else "DISABLE"
    for table in TABLES:
        op.execute(f'ALTER TABLE "{table}" {action} ROW LEVEL SECURITY')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_checkpoint_blobs",
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("checkpoint_ns", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("value_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "channel",
            "version",
            name=op.f("pk_graph_checkpoint_blobs"),
        ),
    )
    op.create_table(
        "graph_checkpoint_writes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("checkpoint_ns", sa.String(length=255), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=255), nullable=False),
        sa.Column("value_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.LargeBinary(), nullable=False),
        sa.Column("task_path", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_checkpoint_writes")),
        sa.UniqueConstraint(
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name=op.f("uq_graph_checkpoint_writes_thread_id"),
        ),
    )
    op.create_index(
        op.f("ix_graph_checkpoint_writes_thread_id"),
        "graph_checkpoint_writes",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "graph_checkpoints",
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("checkpoint_ns", sa.String(length=255), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=64), nullable=False),
        sa.Column("parent_checkpoint_id", sa.String(length=64), nullable=True),
        sa.Column("checkpoint_type", sa.String(length=32), nullable=False),
        sa.Column("checkpoint", sa.LargeBinary(), nullable=False),
        sa.Column("metadata_type", sa.String(length=32), nullable=False),
        sa.Column("metadata_value", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "checkpoint_id", name=op.f("pk_graph_checkpoints")
        ),
    )
    # ### end Alembic commands ###
    _set_rls(True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("graph_checkpoints")
    op.drop_index(
        op.f("ix_graph_checkpoint_writes_thread_id"), table_name="graph_checkpoint_writes"
    )
    op.drop_table("graph_checkpoint_writes")
    op.drop_table("graph_checkpoint_blobs")
    # ### end Alembic commands ###
